In [8]:
l=list(map(str,input().split()))
sum=0
summ=0
for i in l:
    sum+=int(i[1:-1])
print(sum)    

123 123 123
6


## Data Analysis
~Any useful information is called as data.
~Types of data in devices
       -.txt,.img,.ppt,.mp3,.excel,.doc etc.
~Types of data in realtime
- 1.**Quantitative data
~Represents the size/volume of data
   - Discrete and continuous
Discrete :Data is constant/fixed
  - Ex:numbers in a dice,color,nationality etc.
 ~continuous data means the VALUE/DATA is continuous  
   - Ex : time,height,weight
- 2.**Qualitative data 
    

In [2]:
## numpy
import numpy as np
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [11]:
np.__version__


'1.18.5'

In [12]:
# numpy means numerical python
# which is used to deal with array ans scientific 
# computation

In [13]:
np.array([1,2,3,4,5,6,8])

array([1, 2, 3, 4, 5, 6, 8])

In [14]:
np.array([1,2,5,3,4,5],dtype="float")

array([1., 2., 5., 3., 4., 5.])

In [15]:
np.array([1,2,5,3,4,5],dtype="int")

array([1, 2, 5, 3, 4, 5])

In [16]:
np.array([1,2,5,3,4,5],dtype="str")

array(['1', '2', '5', '3', '4', '5'], dtype='<U1')

In [23]:
np.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.array(range(10,100))

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [24]:
np.array(range(1,100,3))

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [25]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [6]:
a.ndim

NameError: name 'a' is not defined

In [28]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
b.ndim #no of dimensions

2

In [30]:
b.size #no of elements in array

6

In [32]:
b.shape #no of rows and columns

(2, 3)

In [34]:
b.dtype

dtype('int32')

In [44]:
c=np.array([[[1,2],[3,4],[5,6]]])
c

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [45]:
c.ndim

3

In [46]:
c.size

6

In [47]:
c.shape

(1, 3, 2)

In [48]:
c.size

6

In [49]:
c.dtype

dtype('int32')

In [50]:
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [51]:
c[0][0]

array([1, 2])

In [52]:
c[0,0]

array([1, 2])

In [53]:
c[0][0][0]

1

In [54]:
 print(np.array([1,2,3,4,5],ndmin=3))

[[[1 2 3 4 5]]]


In [56]:
a=np.array(np.eye(4),dtype='int')
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [60]:
a=np.array(np.ones((4,4),dtype='int'))
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [63]:
a=(np.array(np.zeros((4,4),dtype='int')))
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [64]:
b.fill(4)
b

array([[4, 4, 4],
       [4, 4, 4]])

In [3]:
a=np.array(np.full((4,4),7))
print('Before :\n',a)
a.fill(6)
print('After :\n',a)

Before :
 [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]
After :
 [[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [4]:
print(np.arange(25))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [5]:
print(np.arange(20,101,4))

[ 20  24  28  32  36  40  44  48  52  56  60  64  68  72  76  80  84  88
  92  96 100]


In [6]:
print(np.arange(50,0,-2))

[50 48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10  8  6  4
  2]


In [7]:
a=np.arange(12)
a.reshape(1,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [8]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
print(np.random.randint(10))

1


In [14]:
lw,uw=int(input()),int(input())
a=np.random.randint(lw,uw,8)
a=reshape(2,4)

1
10


NameError: name 'reshape' is not defined

In [15]:
a=np.linspace(3,20)
a

array([ 3.        ,  3.34693878,  3.69387755,  4.04081633,  4.3877551 ,
        4.73469388,  5.08163265,  5.42857143,  5.7755102 ,  6.12244898,
        6.46938776,  6.81632653,  7.16326531,  7.51020408,  7.85714286,
        8.20408163,  8.55102041,  8.89795918,  9.24489796,  9.59183673,
        9.93877551, 10.28571429, 10.63265306, 10.97959184, 11.32653061,
       11.67346939, 12.02040816, 12.36734694, 12.71428571, 13.06122449,
       13.40816327, 13.75510204, 14.10204082, 14.44897959, 14.79591837,
       15.14285714, 15.48979592, 15.83673469, 16.18367347, 16.53061224,
       16.87755102, 17.2244898 , 17.57142857, 17.91836735, 18.26530612,
       18.6122449 , 18.95918367, 19.30612245, 19.65306122, 20.        ])

In [16]:
a=np.linspace(1,1)
a

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
b=np.arange(20).reshape(4,5)
print(b)
print(b.transpose())

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


In [18]:
np.random.randn()

1.0859266223514343

In [19]:
b=np.arange(25)
a[2:4]

array([1., 1.])

In [8]:
a=np.arange(10).reshape(2,5)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [22]:
print(a[0][0:2])

[0 1]


In [23]:
print(a[1][1:3])

[6 7]


In [5]:
## Arithmetic operations on arrays
#+,-,*,/
a

NameError: name 'a' is not defined

In [25]:
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
a+a

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [28]:
a-a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [29]:
a*a

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [31]:
a//a

<ipython-input-31-932792481982>:1: RuntimeWarning: divide by zero encountered in floor_divide
  a//a


array([[0, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [32]:
np.log(1)

0.0

In [33]:
a=np.log([1,2,3,4])
a

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [35]:
a=np.sin([1,2,3,4])
a

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [39]:
print(f'ARRAY :\n {a} \n Minimum : {np.amin(a)} \n Maximum : {np.amax(a)} \n Mean {np.mean(a)}  \n Median {np.median(a)}') 

ARRAY :
 [ 0.84147098  0.90929743  0.14112001 -0.7568025 ] 
 Minimum : -0.7568024953079282 
 Maximum : 0.9092974268256817 
 Mean 0.2837714810963793  
 Median 0.4912954964338819


In [9]:
np.amin(a)

0

In [10]:
print(np.std(a))

2.8722813232690143


In [11]:
print(np.var(a))

8.25
